In [2]:
from nltk.tokenize import TreebankWordTokenizer
eng_tokenizer = TreebankWordTokenizer()
eng_tokenizer.tokenize('certificates related to teaching preferred. For non-native English speakers')

['certificates',
 'related',
 'to',
 'teaching',
 'preferred.',
 'For',
 'non-native',
 'English',
 'speakers']

In [16]:
callable(eng_tokenizer.tokenize)

True

In [8]:
eng_tokenizer.tokenize('certificates, related/to teaching preferredอาหาร . For .non-native English-speakers')

['certificates',
 ',',
 'related/to',
 'teaching',
 'preferredอาหาร',
 '.',
 'For',
 '.non-native',
 'English-speakers']

In [9]:
mlst = [1,2,3]
mlst[:-0]

[]

In [11]:
list(range(2))

[0, 1]

In [22]:
doc01 = 'Full-time (เต็มเวลา) English Language Teacher.'

In [23]:
doc02 = 'Full-time (เต็มเวลา) and part-time (นอกเวลา) Chinese Language Teacher'

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(tokenizer=eng_tokenizer.tokenize)
vectorizer

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<bound method TreebankWordTokenizer.tokenize of <nltk.tokenize.treebank.TreebankWordTokenizer object at 0x000001935571AD30>>,
        vocabulary=None)

In [24]:
corpus = [doc01, doc02]

In [25]:
X = vectorizer.fit_transform(corpus)
X

<2x12 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

In [26]:
X.toarray()

array([[1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1],
       [2, 2, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1]], dtype=int64)

In [36]:
print(eng_tokenizer.tokenize(doc01))
print(eng_tokenizer.tokenize(doc02))
vocab_dict = {'full-time':0, 'english':1, 'เต็มเวลา':2, 'chinese':3, 'language':4}
vectorizer_red = CountVectorizer(tokenizer=eng_tokenizer.tokenize, vocabulary=vocab_dict, ngram_range=(1, 2))
Y = vectorizer_red.fit_transform(corpus)
Y.toarray()

['Full-time', '(', 'เต็มเวลา', ')', 'English', 'Language', 'Teacher', '.']
['Full-time', '(', 'เต็มเวลา', ')', 'and', 'part-time', '(', 'นอกเวลา', ')', 'Chinese', 'Language', 'Teacher']


array([[1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1]], dtype=int64)

In [39]:
analyse = vectorizer_red.build_analyzer()
analyse(doc01)

['full-time',
 '(',
 'เต็มเวลา',
 ')',
 'english',
 'language',
 'teacher',
 '.',
 'full-time (',
 '( เต็มเวลา',
 'เต็มเวลา )',
 ') english',
 'english language',
 'language teacher',
 'teacher .']

In [51]:
vocab_dict = {'full-time':0, 'english':1, 'เต็มเวลา':2, 'chinese':3, 'language':4}
vectorizer_bi = CountVectorizer(tokenizer=eng_tokenizer.tokenize, ngram_range=(1, 2))
Y = vectorizer_bi.fit_transform(['full-time english chinese language', 'part-time chinese language'])
Y.toarray()

array([[1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 1]], dtype=int64)

In [52]:
vectorizer_bi.vocabulary_

{'chinese': 0,
 'chinese language': 1,
 'english': 2,
 'english chinese': 3,
 'full-time': 4,
 'full-time english': 5,
 'language': 6,
 'part-time': 7,
 'part-time chinese': 8}

In [56]:
import sys
sys.path.append('..')
from tokenizer import tokenizer as my_tokenizer

In [57]:
print(sys.path)

['', 'c:\\users\\nutha\\jpa\\scripts\\python36.zip', 'C:\\Program Files\\Python36\\DLLs', 'C:\\Program Files\\Python36\\lib', 'C:\\Program Files\\Python36', 'c:\\users\\nutha\\jpa', 'c:\\users\\nutha\\jpa\\lib\\site-packages', 'c:\\users\\nutha\\jpa\\lib\\site-packages\\pip-9.0.1-py3.6.egg', 'c:\\users\\nutha\\jpa\\lib\\site-packages\\IPython\\extensions', 'C:\\Users\\nutha\\.ipython', '..']


In [58]:
tkn = my_tokenizer(3)

c:\users\nutha\jpa\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


Instructions for updating:
`NHWC` for data_format is deprecated, use `NWC` instead


In [59]:
tri_vectorizer = CountVectorizer(tokenizer=tkn.tokenizer)
X = tri_vectorizer.fit_transform(corpus)
print(X.toarray())

[[1 0 0 1 1 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0
  1 1 1 1 1 0 0 1]
 [2 1 1 1 1 2 1 1 1 1 0 0 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1
  1 1 1 2 2 1 1 0]]


In [60]:
tri_vectorizer.vocabulary_

{'(': 0,
 '(นอก': 1,
 '(นอกเวลา': 2,
 '(เต็ม': 3,
 '(เต็มเวลา': 4,
 ')': 5,
 ')and': 6,
 ')andpart-time': 7,
 ')chinese': 8,
 ')chineselanguage': 9,
 ')english': 10,
 ')englishlanguage': 11,
 '.': 12,
 'and': 13,
 'andpart-time': 14,
 'andpart-time(': 15,
 'chinese': 16,
 'chineselanguage': 17,
 'chineselanguageteacher': 18,
 'english': 19,
 'englishlanguage': 20,
 'englishlanguageteacher': 21,
 'full-time': 22,
 'full-time(': 23,
 'full-time(เต็ม': 24,
 'language': 25,
 'languageteacher': 26,
 'languageteacher.': 27,
 'part-time': 28,
 'part-time(': 29,
 'part-time(นอก': 30,
 'teacher': 31,
 'teacher.': 32,
 'นอก': 33,
 'นอกเวลา': 34,
 'นอกเวลา)': 35,
 'เต็ม': 36,
 'เต็มเวลา': 37,
 'เต็มเวลา)': 38,
 'เวลา': 39,
 'เวลา)': 40,
 'เวลา)and': 41,
 'เวลา)chinese': 42,
 'เวลา)english': 43}